algoritmo "estudo"
// Função : Nada
// Autor : Yuri Cavalcanti Gonçalves
// Data : 20/04/2018
// Seção de Declarações 
var
n:caractere
i:inteiro
inicio
escreva("Nome:")                                             
leia(n)
escreva("Idade:")
leia(i)
se (i<18) entao
escreval("Jovem")
fimse
se (i>=18) entao
escreval("adulto")
fimse
se (i>75) entao
escreval("idoso")
fimse
fimalgoritmo
